module.exports = { 
    "brott": [
        "Allmänfarlig vårdslöshet",
        "Allmänfarlig ödeläggelse",
        "Arbetsmiljöbrott",
        "Bedrägeri",
        "Bedrägligt beteende",
        "Behörighetsmissbruk",
        "Bestickning",
        "Bevisförvanskning",
        "Bokföringsbrott",
        "Bristande tillsyn",
        "Brott mot 12 kap 65 § jordabalken",
        "Brott mot griftefrid",
        "Brott mot medborgerlig frihet",
        "Brott mot rösthemlighet",
        "Trafikförordningen",
        "Brott mot tystnadsplikt",
        "Brukande av osann urkund",
        "Brytande av post- eller telehemlighet",
        "Dataintrång",
        "Dobbleri",
        "Egenmäktighet vid förhandling med främmande makt",
        "Egenmäktigt förfarande",
        "Falsk angivelse",
        "Falsk tillvitelse",
        "Falskt larm",
        "Falskt åtal",
        "Folkrättsbrott",
        "Framkallande av fara för annan",
        "Främjande av flykt",
        "Fyndförseelse",
        "Förargelseväckande beteende",
        "Föregivande av allmän ställning",
        "Förfalskning",
        "Förgripelse mot tjänsteman",
        "Förgöring",
        "Förledande av ungdom",
        "Förnekande av underskrift",
        "Förolämpning",
        "Förskingring",
        "krigsförberedelse",
        "Försvårande av skattekontroll",
        "Förtal",
        "Förvanskande av familjeställning",
        "Förvanskning av urkund",
        "Grov fridskränkning",
        "Hemfridsbrott",
        "Hets mot folkgrupp",
        "Hindrande av förrättning",
        "Häleri",
        "Häleriförseelse",
        "Högförräderi",
        "Inbrott",
        "Incest",
        "Intrång i förvar",
        "Kapning",
        "Koppleri",
        "Krigsanstiftan",
        "Landsförräderi",
        "Landsskadlig vårdslöshet",
        "Landssvek",
        "Lydnadsbrott",
        "Mannamån mot borgenärer",
        "Missbruk av larmanordning",
        "Missbruk av urkund",
        "Misshandel",
        "Mutbrott",
        "Myteri",
        "Människohandel",
        "Människorov",
        "kidnappning",
        "Märkesförfalskning",
        "Narkotikabrott",
        "Nedskräpning",
        "Nekrofili",
        "Obefogad angivelse",
        "Obefogat åtal",
        "Obehörig befattning med hemligt uppgift",
        "Obehörig kapitulation",
        "Ocker",
        "Ockerpantning",
        "Ofredande",
        "Ohörsamhet mot ordningsmakten",
        "Olaga diskriminering",
        "Olaga frihetsberövande",
        "Olaga hot",
        "Olaga intrång",
        "Olaga spridande av efterbildning",
        "Olaga tvång",
        "Olaga våldsskildring",
        "Olovlig avlyssning",
        "Olovlig befattning med falska pengar",
        "Olovlig befattning med kemiska vapen",
        "Olovlig befattning med minor",
        "Olovlig kraftavledning",
        "Olovlig kårverksamhet",
        "Olovlig kärnsprängning",
        "Olovligt brukande",
        "Olovligt förfogande",
        "Olovligt ingående av äktenskap",
        "Olovligt partnerskap",
        "Olovlig underrättelseverksamhet",
        "Olovlig värvning",
        "Oredlighet mot borgenärer",
        "Oredligt förfarande",
        "Osann försäkran",
        "Osann partsutsaga",
        "Osann utsaga inför en internationell domstol",
        "Osann utsaga inför nordisk domstol",
        "Osant intygande",
        "Otillbörligt verkande vid röstning",
        "Otillåten utlämning av teknisk upptagning",
        "Otillåtet förfarande med pornografisk bild",
        "Ovarsam utsaga",
        "Ovarsam utsaga inför internationell domstol",
        "Ovarsam utsaga inför nordisk domstol",
        "Penningförfalskning",
        "Penninghäleri",
        "Penninghäleriförseelse",
        "Rattfylleri",
        "Ryktesspridning till fara för rikets säkerhet",
        "Rymning",
        "Rån",
        "Sabotage",
        "Samröre med fienden",
        "Signaturförfalskning",
        "Självtäkt",
        "Sjöfylleri",
        "Skadegörelse",
        "Skatteavdragsbrott",
        "Skattebrott",
        "Skatteförseelse",
        "Skatteredovisningsbrott",
        "Skyddande av brottsling",
        "Smitning",
        "Snatteri",
        "Spioneri",
        "Spridande av gift eller smitta",
        "Stridsförsumlighet",
        "Störande av förrättning eller av allmän sammankomst",
        "Subventionsmissbruk",
        "Svikande av försvarsplikt",
        "Svindleri",
        "Tagande av olovlig väg",
        "Tagande av otillbörlig belöning vid röstning",
        "Tagande av utländskt understöd",
        "Tillgrepp av fortskaffningsmedel",
        "Tjänstebrott",
        "Tjänstefel",
        "Trolöshet mot huvudman",
        "Trolöshet vid förhandling med främmande makt",
        "Tvegifte",
        "Undandräkt",
        "Undergrävande av stridsviljan",
        "Underlåtenhet att avvärja allmänfara",
        "Underlåtenhet att avvärja rättsfel",
        "Undertryckande av urkund",
        "Uppror",
        "Uppvigling",
        "Urkundsförfalskning",
        "Utpressning",
        "Vållande till annans död",
        "Vållande till kroppsskada eller sjukdom",
        "Vårdslös försäkran",
        "Vårdslös skatteredovisning",
        "Vårdslös skatteuppgift",
        "Vårdslös tillvitelse",
        "Vårdslöshet i trafik",
        "Vårdslöshet med gift eller smittämne",
        "Vårdslöshet med hemlig uppgift",
        "Vårdslöshet mot borgenärer",
        "Åverkan",
        "Övergrepp i rättssak",
        "Överträdelse av myndighets bud"
    ]
}